### ISSUE TITLE
Quitmessages are visible even when premiumvanish vanishmode active

### ISSUE THREAD

**Issue by CubBossa** [MultiChat/Development#167]
**Describe the bug**
When i turn into vanish with the plugin premium vanish it all works fine. On quit it gives the online players a message though. So they can know that I was in vanish because i have two quit messages.

**Full startup log of affected servers**
```
[18:14:06] [main/INFO]: Using mbed TLS based native cipher.
[18:14:06] [main/INFO]: Using zlib based native compressor.
[18:14:06] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395
[18:14:07] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[18:14:07] [main/INFO]: Epoll is working, utilising it!
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[18:14:07] [main/INFO]: Loaded plugin MiniMOTD version 2.0.0 by jmp
[18:14:07] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:09] [main/INFO]: Loaded plugin LuckPerms version 5.2.76 by Luck
[18:14:09] [main/INFO]: Loaded plugin BungeeWhiteList version 1.0 by xGabryMC
[18:14:09] [main/INFO]: Loaded plugin BungeeMail version 1.10 by CodeCrafter47
[18:14:09] [main/INFO]: Loaded plugin MultiChat version 1.9.6 by Revilo410
[18:14:09] [main/INFO]: Loaded plugin PremiumVanish version 2.6.6 by MyzelYam
[18:14:09] [main/INFO]: Loaded plugin AdvancedBanAutoBan version 1.0.2 by james090500
[18:14:09] [main/INFO]: Loaded plugin OnlineTime version 2.0.2 by seyfahni and Mr_Minecraft15
[18:14:09] [main/INFO]: Loaded plugin protocolize-plugin version 1.6.8-SNAPSHOT:446 by Exceptionflug
[18:14:09] [main/INFO]: Loaded plugin NuVotifier version 2.7.2 by Ichbinjoe, blakeman8192, Kramer, tuxed
[18:14:09] [main/INFO]: Loaded plugin BungeePluginManager version 2.0 by _Shevchik_
[18:14:09] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:09] [main/WARN]: Error enabling plugin PlaceholderAPI
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:44) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:381) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:285) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:277) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:63) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:37) ~[waterfall-1.16-395.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:c031df1:395]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	... 17 more
[18:14:09] [main/INFO]: Loaded plugin MoveMeNow version 1.2-CUSTOMBUILD by roblabla
[18:14:09] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:09] [main/INFO]: Loaded plugin AdvancedBan version 2.2.1 by Leoko
[18:14:09] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:09] [main/INFO]: Loaded plugin BasisBungee version 1.0.0 by cubbossa
[18:14:09] [main/INFO]: Loaded plugin BuycraftX version 12.0.6 by Buycraft
[18:14:09] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:09] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:10] [main/INFO]: Loaded plugin BungeeTabListPlus version 3.4.1-SNAPSHOT by CodeCrafter47
[18:14:10] [main/WARN]: Forced host server pvp is not defined
[18:14:11] [main/INFO]: Enabled plugin MiniMOTD version 2.0.0 by jmp
[18:14:11] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:12] [main/INFO]:         __    
[18:14:12] [main/INFO]:   |    |__)   LuckPerms v5.2.76
[18:14:12] [main/INFO]:   |___ |      Running on BungeeCord - Waterfall
[18:14:12] [main/INFO]: 
[18:14:12] [main/INFO] [LuckPerms]: Loading configuration...
[18:14:13] [main/INFO] [LuckPerms]: Loading storage provider... [MYSQL]
[18:14:13] [main/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Starting...
[18:14:13] [main/INFO] [me.lucko.luckperms.lib.hikari.HikariDataSource]: luckperms-hikari - Start completed.
[18:14:14] [MiniMOTD Pool Thread #0/INFO] [MiniMOTD]: You are running the latest version of MiniMOTD! :)
[18:14:14] [main/INFO] [LuckPerms]: Loading messaging service... [SQL]
[18:14:15] [main/INFO] [LuckPerms]: Loading internal permission managers...
[18:14:15] [main/INFO] [LuckPerms]: Performing initial data load...
[18:14:16] [main/INFO] [LuckPerms]: Successfully enabled. (took 5187ms)
[18:14:16] [main/INFO]: Enabled plugin LuckPerms version 5.2.76 by Luck
[18:14:16] [main/INFO]: Enabled plugin BungeeWhiteList version 1.0 by xGabryMC
[18:14:16] [main/INFO]: Enabled plugin BungeeMail version 1.10 by CodeCrafter47
[18:14:16] [main/INFO]: Config file config.yml not found... Creating new one.
[18:14:16] [main/INFO]: Loading joinmessages.yml...
[18:14:16] [main/INFO]: Loading messages.yml...
[18:14:16] [main/INFO]: Loading chatcontrol.yml...
[18:14:16] [main/INFO]: Loading messages_fr.yml...
[18:14:16] [main/INFO]: Loading joinmessages_fr.yml...
[18:14:16] [main/INFO]: Loading config_fr.yml...
[18:14:16] [main/INFO]: Loading chatcontrol_fr.yml...
[18:14:17] [main/INFO]: [MultiChat] Config Version: 1.9.6
[18:14:17] [main/INFO]: [MultiChat] Starting load routine for data files
[18:14:17] [main/INFO]: [MultiChat] [COMPLETE] Load sequence finished! (Any errors reported above)
[18:14:17] [main/INFO]: [MultiChat] Hooked with PremiumVanish!
[18:14:17] [main/INFO]: Enabled plugin MultiChat version 1.9.6 by Revilo410
[18:14:18] [main/INFO] [PremiumVanish]: Successfully connected to the database.
[18:14:18] [main/INFO] [PremiumVanish]: Hooking into Waterfall for server query support
[18:14:18] [main/INFO]: Enabled plugin PremiumVanish version 2.6.6 by MyzelYam
[18:14:18] [main/INFO] [AdvancedBanAutoBan]: Plugin Loaded
[18:14:18] [main/INFO] [AdvancedBanAutoBan]: This plugin is in early alpha! Please report any bugs!
[18:14:18] [main/INFO]: Enabled plugin AdvancedBanAutoBan version 1.0.2 by james090500
[18:14:18] [main/INFO] [OnlineTime]: Enabled OnlineTimeStorageRequestListener.
[18:14:18] [main/INFO]: Enabled plugin OnlineTime version 2.0.2 by seyfahni and Mr_Minecraft15
[18:14:18] [main/INFO]: ======= PROTOCOLIZE =======
[18:14:18] [main/INFO]: Version 1.6.8-SNAPSHOT:446 by Exceptionflug
[18:14:18] [main/INFO]: [Protocolize] Running on Waterfall. Please report bugs regarding protocolize at https://github.com/Exceptionflug/protocolize/issues
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.ChangeGameState
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.NamedSoundEffect
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPosition
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerLook
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPositionLook
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.SetSlot
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.WindowItems
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.UseItem
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.BlockPlacement
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.OpenWindow
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.WindowProperty
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[18:14:18] [main/WARN]: [Protocolize] Protocol version 755 is not supported on this waterfall version. Skipping registration for that specific version.
[18:14:18] [main/INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ClickWindow
[18:14:18] [main/INFO]: Enabled plugin protocolize-plugin version 1.6.8-SNAPSHOT:446 by Exceptionflug
[18:14:18] [main/INFO] [NuVotifier]: Loaded token for website: default
[18:14:18] [NuVotifier Pool Thread #0/INFO] [NuVotifier]: Using epoll transport to accept votes.
[18:14:18] [main/INFO] [NuVotifier]: Method none selected for vote forwarding: Votes will not be forwarded to backend servers.
[18:14:18] [main/INFO]: Enabled plugin NuVotifier version 2.7.2 by Ichbinjoe, blakeman8192, Kramer, tuxed
[18:14:18] [main/INFO]: Enabled plugin BungeePluginManager version 2.0 by _Shevchik_
[18:14:18] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:18] [main/INFO]: Enabled plugin MoveMeNow version 1.2-CUSTOMBUILD by roblabla
[18:14:18] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:18] [Votifier epoll boss/INFO] [NuVotifier]: Votifier enabled on socket /0:0:0:0:0:0:0:0%0:8194.
[18:14:19] [main/INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[18:14:19] [main/INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[18:14:19] [main/INFO]: 
 
[]=====[Enabling AdvancedBan]=====[]
| Information:
|   Name: AdvancedBan
|   Developer: Leoko
|   Version: 2.2.1
|   Storage: MySQL (external)
| Support:
|   Github: https://github.com/DevLeoko/AdvancedBan/issues
|   Discord: https://discord.gg/ycDG6rS
| Twitter: @LeokoGar
| Update:
|   There is a new version available! [2.3.0]
[]================================[]
 
[18:14:19] [main/INFO]: Enabled plugin AdvancedBan version 2.2.1 by Leoko
[18:14:19] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:19] [main/INFO]: [BasisBungee] Plugin erkannt und hochgefahren
[18:14:19] [main/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[18:14:19] [main/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[18:14:19] [main/INFO]: [BasisBungee] Verbindung zu MYSQL-Datenbank aufgebaut!
[18:14:19] [main/INFO]: Command: gemadmin registriert
[18:14:19] [main/INFO]: Command: tpa registriert
[18:14:19] [main/INFO]: Command: tp registriert
[18:14:19] [main/INFO]: Command: tpahere registriert
[18:14:19] [main/INFO]: Command: tphere registriert
[18:14:19] [main/INFO]: Command: tpaccept registriert
[18:14:19] [main/INFO]: Command: tpadeny registriert
[18:14:19] [main/INFO]: Command: info registriert
[18:14:19] [main/INFO]: Command: infojeff registriert
[18:14:19] [main/INFO]: Command: infoemojis registriert
[18:14:19] [main/INFO]: Enabled plugin BasisBungee version 1.0.0 by cubbossa
[18:14:19] [main/INFO] [BuycraftX]: Validating your server key...
[18:14:20] [main/INFO]: Enabled plugin BuycraftX version 12.0.6 by Buycraft
[18:14:20] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:20] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:c031df1:395 by WaterfallMC
[18:14:21] [main/INFO] [BungeeTabListPlus]: Starting UpdateChecker Task
[18:14:21] [BuycraftX Pool Thread #1/INFO] [BuycraftX]: Fetching all due players...
[18:14:22] [BuycraftX Pool Thread #1/INFO] [BuycraftX]: Fetched due players (0 found).
[18:14:22] [main/INFO]: Enabled plugin BungeeTabListPlus version 3.4.1-SNAPSHOT by CodeCrafter47
[18:14:22] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:25565
[18:15:17] [MultiChat Pool Thread #1/INFO] [MultiChat]: Commencing backup!
[18:15:17] [MultiChat Pool Thread #1/INFO] [MultiChat]: Backup complete. Any errors reported above.
```

**To Reproduce**
1. Install a fresh copy of multichat 1.9.6 and PremiumVanish 2.6.6
2. Start up version 'waterfall-1.16-395.jar' of Bungeecord
3. Hide yourself with /v and reconnect
4. Other users will see you disconnect but not connect.

**Expected behavior**
Nothing ^^ there should be no disconnect message because the players are supposed to think that youre not there.

**Screenshots**
![Uploading 2021-02-23_18.31.03.png…]()
So i turned CubBossas vanish off and on (marked with a . infront of [+]) and then reconnected and turned vanish off.
The message without the dot is the real disconnect and should not be displayed.

**Platform and Versions (please complete the following information):**
 - OS: debian 10
 - Java Version: 11
 - MultiChat Version: 1.9.6
 - Proxy Version: waterfall-1.16-395.jar
 - Local Server Version: paper-1.16.5-466.jar
 - PremiumVanish 2.6.6

**Additional context**

**Comment by ChipWolf** [comment]
I don't see a `silence_leave` option, this is a feature request, not a bug
