### ISSUE TITLE
Players getting kicked when other players join

### ISSUE THREAD

**Issue by phit** [MultiChat/Development#2]
Doesn't happen all the time, but happens enough to be annoying :/
SpongeForge 1.10.2-2221-5.1.0-BETA-2136

```
[15:38:52] [Netty Epoll Server IO #4/ERROR] [FML/]: There was a critical exception handling a packet on channel MultiChat
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_121]
	at com.olivermartin410.plugins.MultiChatRawDataListener.handlePayload(MultiChatRawDataListener.java:24) ~[MultiChatRawDataListener.class:?]
	at org.spongepowered.mod.network.SpongeRawChannel.handlePacket(SpongeRawChannel.java:91) ~[SpongeRawChannel.class:1.10.2-2221-5.1.0-BETA-2136]
	at org.spongepowered.mod.network.SpongeRawDataInboundHandler.channelRead0(SpongeRawDataInboundHandler.java:50) ~[SpongeRawDataInboundHandler.class:1.10.2-2221-5.1.0-BETA-2136]
	at org.spongepowered.mod.network.SpongeRawDataInboundHandler.channelRead0(SpongeRawDataInboundHandler.java:36) ~[SpongeRawDataInboundHandler.class:1.10.2-2221-5.1.0-BETA-2136]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) ~[AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:100) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:149) [eo.class:?]
	at net.minecraft.network.NetworkManager.channelRead0(NetworkManager.java:51) [eo.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.handleServerSideCustomPacket(NetworkDispatcher.java:446) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:269) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.channelRead0(NetworkDispatcher.java:73) [NetworkDispatcher.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [ByteToMessageDecoder.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [ReadTimeoutHandler.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [AbstractChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [DefaultChannelPipeline.class:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [EpollSocketChannel$EpollSocketUnsafe.class:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [EpollEventLoop.class:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [EpollEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]

```

**Comment by OllieMartin** [comment]
Hi there,

Sorry to hear about that, I am currently looking into the issue!

**Comment by OllieMartin** [comment]
Hey,
I dont think the underlying issue is actually to do with multichat iteself. It seems that the plugin is trying to get data for a player who for some reason no longer exists. I have patched this so that if the issue does occur and the plugin for some reason hasn't been given data for a player it will just ignore it with a little warning message to the console screen. If it still kicks them from the server then I dont think it is my plugin which is causing the issue Im afraid :/ 
I hope that this will fix it for you! I havent yet posted to the update to spigot or sponge, but when I do I will reply back here and close the issue :)

Thanks!

**Comment by phit** [comment]
To clarify, it kicks another random person from the server, not the person who just joined. Thanks for looking into this!

**Comment by OllieMartin** [comment]
Mmm thanks interesting... What I think we will have to do is see if the updated version fixes the issue, but if it doesnt then please sent me the error messages again on here and I'll take another look at everything. Is that the only message that is displayed? Are there any other error messages other than the player being kicked?

**Comment by phit** [comment]
I didn't see anything relevant, just looked through a months of logs. I did find an instance where the exception occurred for the first player to join right after the server had just restarted, so not sure how it would think the player no longer exists, maybe the info is being called too early?
The second log has the exception 5 times.
[onfirstjoin.txt](https://github.com/MultiChat/Development/files/788678/onfirstjoin.txt)
[5times.txt](https://github.com/MultiChat/Development/files/788679/5times.txt)

**Comment by OllieMartin** [comment]
Yeah I see what you mean, well Im hoping that by simply catching the exception that was being thrown it will stop them being kicked. We will see!

I'm not going to push this to spigot yet, and I havent had a chance to test this jar yet, but here is the latest code! https://github.com/MultiChat/Development/blob/master/multichat/target/multichat-1.4.jar

Give that a try and let me know how it goes!

**Comment by OllieMartin** [comment]
Since that last message you can now find all the snapshot versions of 1.4 here, so when you try it use the latest snapshot :) SNAPSHOT 6 as of writing should definitely be stable. https://github.com/MultiChat/Development/tree/master/multichat/Versions/1.4/1.4.0/Snapshots

**Comment by OllieMartin** [comment]
MultiChat 1.4 has been released and Im pretty sure your issue has been addressed so I am going to close this issue, feel free to reply back here or open a new issue if you still get the problem!

Thanks :)
