### ISSUE TITLE
Bulletin list doesn't work

### ISSUE THREAD

**Issue by Dreandor** [MultiChat/Development#51]
**Describe the bug**
A clear and concise description of what the bug is. Please make separate reports for different bugs!

**Full startup log of affected servers**
```
Paste the FULL startup log of Bungeecord / Spigot here depending on where the issue occurs
```

**To Reproduce**
1. Install a fresh copy of '....'
2. Start up version '....' of Bungeecord
3. Type command '....' in chat

**Expected behavior**

**Screenshots**

**Platform and Versions (please complete the following information):**
 - OS: Debian
 - Java Version: Java 8
 - MultiChat Version: 1.7.3
 - Proxy Version: Bungeecord-1523
 - Local Server Version: [e.g. craftbukkit234, spigot-1256, paperclip-456, spongevanilla-2456]

**Additional context**
Everytime I do /bulletin list 
this come:

17:59:07 [WARNING] Error in dispatching command
java.lang.IllegalArgumentException: Illegal group reference
    at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
    at java.util.regex.Matcher.replaceAll(Matcher.java:955)
    at java.lang.String.replaceAll(String.java:2223)
    at xyz.olivermartin.multichat.bungee.MessageManager.sendSpecialMessage(MessageManager.java:417)
    at xyz.olivermartin.multichat.bungee.commands.BulletinCommand.execute(BulletinCommand.java:50)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:189)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:142)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:145)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:104)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
    at java.lang.Thread.run(Thread.java:748)

**Comment by OllieMartin** [comment]
Apologies for the slow reply, I will attach my message from the Discord to the end which explains my absence.

I cannot reproduce this error, it looks like a strange issue where for some reason a regex error is occuring. New versions of the plugin have been released since when this was posted. If you still have the error please open a new issue and paste your startup log and what bulletins you were trying to use. Many thanks and again apologies for the awful response time!

"Hello @everyone. I'm sure many of you are used to these sort of posts from me now... Firstly, you have my genuine apology for being absent for so long. I have started my new job only recently, and it has been hectic to say the least. I have had absolutely no free time whatsoever to dedicate to the plugin as much as I wish I had. I know a lot of you have been complaining about slow response times, and that the spigot page says "use Discord for fast support!", so again I am sorry that was not the case. However, I would like to extend a huge thanks to those of you in the community who have stepped up and helped everyone out when they needed it. Occasionally I would see notifications relevant to the plugin but just have no time to even look at it properly, but it reassuring to also see notifications answering peoples problems, so again thank you so much for 'holding the deck' so to say.

I am still extremely busy... However, I have slightly more time than before. I am going to aim to spend some time on the plugin in the next few weeks, and I am hoping I will be able to keep up with the support requests from you all here. It would be impossible for me to go through and answer every message that has been said while I have been away, so if you do have any issues please just send them again to the #support channel. I will get back to you ASAP :)

As far as I know the plugin is still in full working order with the current MC version, if it is not then I will try to get this fixed ASAP. I cannot commit to providing lots of new feaures currently because of how busy I am, but I will certainly ensure that the current features are working.

Thank you all for using the plugin as usual, and apologies for the lack of support."
