### ISSUE TITLE
Display name cannot be longer than 16 characters

### ISSUE THREAD

**Issue by apatuka** [MultiChat/Development#86]
**Describe the bug**
On FlameCord (Travertine Fork) it has an warning output that doesn't cause any noticeable error but it fills the console and .log file with more than 1-2GB per day.

**Full startup log of affected servers**
```
[12:29:04 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@6d75138e, receiver=Lolosegovia_PY), cancelled=false, tag=multichat:nick) to listener xyz.olivermartin.multichat.bungee.BungeeComm@12192604
	java.lang.IllegalArgumentException: Display name cannot be longer than 16 characters
		at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
		at net.md_5.bungee.UserConnection.setDisplayName(UserConnection.java:193) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
		at xyz.olivermartin.multichat.bungee.PlayerMetaManager.updateDisplayName(PlayerMetaManager.java:71) ~[?:?]
		at xyz.olivermartin.multichat.bungee.BungeeComm.onPluginMessage(BungeeComm.java:273) ~[?:?]
		at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source) ~[?:?]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
		at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
		at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:384) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:246) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:122) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:94) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:303) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:417) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:9cdd70e:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
```

**To Reproduce**
Install Travertine and the Plugin/
Run server
When you login it throws that error.

**Expected behavior**
Would be nice to have this error hidden.

**Screenshots**
Don't have any

**Platform and Versions (please complete the following information):**
- Ubuntu 16.04
- JAVA 8
- Travertine

**Comment by OllieMartin** [comment]
Hi there,

This is not a 'MultiChat error'. It is a limitation on Minecraft version 1.7. Display names were limited to a maximum of 16 characters.

MultiChat has implemented lots of config options to let it function on 1.7 without causing this error. If you use MultiChat to set your display names (the setting "set_display_name" in the bungeecord config), then you need  to make sure you are not setting the display name to something that is longer than 16 characters long. For example, the player's name, or their nickname (which you can then limit the length of to 16 in the local multichat config on spigot or sponge).

Usually people set the display name to %PREFIX%%NICK% for example, but this will not work on minecraft version 1.7 as it will exceed 16 characters most likely.

You can still use all your prefixes everywhere else, for example in the global chat format, local chat format etc. But you just cannot have all that in the displayname or it exceeds the limit.

I hope that helps, if you need any more guidance just let me know :)
