### ISSUE TITLE
onDisable() java.util.NoSuchElementException

### ISSUE THREAD

**Issue by FaberoM** [MultiChat/Development#99]
**Describe the bug**
Getting this error when shutting down the server. The line 222 suggests it's MySQL related.

**Full ~~startup~~ shutdown log of affected servers**
No problems on startup so I'm just gonna leave the shutdown log here.
```
[23:00:43 INFO]: Stopping the server
[23:00:43 INFO]: Stopping server
[23:00:43 INFO]: [HolographicExtension] Disabling HolographicExtension v1.10.9
[23:00:43 INFO]: [HolographicExtension] Disabling HolographicExtension v1.10.9
[23:00:43 INFO]: [HolographicDisplays] Disabling HolographicDisplays v2.4.1
[23:00:43 INFO]: [ItemJoin] Disabling ItemJoin v5.0.6-RELEASE-b395
[23:00:43 INFO]: [ItemJoin] has been Disabled.
[23:00:43 INFO]: [TAB] Disabling TAB v2.7.4
[23:00:43 INFO]: [TAB] Disabled in 0ms
[23:00:43 INFO]: [FakeDimension] Disabling FakeDimension v1.1
[23:00:43 INFO]: [PremiumVanish] Disabling PremiumVanish v2.5.11
[23:00:43 INFO]: [com.zaxxer.hikari.HikariDataSource] PremiumVanish - Shutdown initiated...
[23:00:43 INFO]: [com.zaxxer.hikari.HikariDataSource] PremiumVanish - Shutdown completed.
[23:00:43 INFO]: [MultiChat] Disabling MultiChat v1.9
[23:00:43 ERROR]: Error occurred while disabling MultiChat v1.9 (Is it up to date?)
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:141) ~[?:?]
at xyz.olivermartin.multichat.local.spigot.MultiChatLocalSpigotPlugin.onDisable(MultiChatLocalSpigotPlugin.java:222) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-245]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:405) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:741) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-245]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:992) ~[patched_1.15.2.jar:git-Paper-245]
at java.lang.Thread.run(Thread.java:832) [?:?]
[23:00:43 INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.0
[23:00:43 INFO]: [WorldGuard] Disabling WorldGuard v7.0.2-SNAPSHOT;bf2593e
[23:00:43 INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[23:00:43 INFO]: [SimpleSit] Disabling SimpleSit v0.1.5
[23:00:43 INFO]: [F3NPerm] Disabling F3NPerm v2.3
[23:00:43 INFO]: [F3NPerm] Plugin disabled!
[23:00:43 INFO]: [Vault] Disabling Vault v1.7.2-b107
[23:00:43 INFO]: WEPIF: Vault detected! Using Vault for permissions
[23:00:43 INFO]: [PlugMan] Disabling PlugMan v2.1.7
[23:00:43 INFO]: [WAEssentials] Disabling WAEssentials v0.8.0
[23:00:43 INFO]: [PlaceholderAPI] Disabling PlaceholderAPI v2.10.6
[23:00:43 INFO]: [WorldEdit] Disabling WorldEdit v7.1.0;8e55131
[23:00:43 INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[23:00:43 INFO]: [AdvancedPortals] Disabling AdvancedPortals v0.5.2
[23:00:43 INFO]: Advanced portals are being disabled!
[23:00:43 INFO]: [LuckPerms] Disabling LuckPerms v5.0.136
[23:00:43 INFO]: [LuckPerms] Starting shutdown process...
[23:00:43 INFO]: [LuckPerms] Closing messaging service...
[23:00:43 INFO]: [LuckPerms] Closing storage...
[23:00:43 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Shutdown initiated...
[23:00:43 INFO]: [me.lucko.luckperms.lib.hikari.HikariDataSource] luckperms-hikari - Shutdown completed.
[23:00:43 INFO]: [LuckPerms] Goodbye!
[23:00:43 INFO]: Saving players
[23:00:43 INFO]: Saving worlds
[23:00:43 INFO]: Saving chunks for level 'world'/minecraft:overworld
[23:00:43 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[23:00:43 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[23:00:43 INFO]: Flushing Chunk IO
[23:00:43 INFO]: Closing Thread Pool
[23:00:43 INFO]: Closing Server
```

**To Reproduce**
1. Install MultiChat on both Bungee(Waterfall) and Spigot(Paper)
2. Have MySQL enabled (nickname too?)
3. Turn spigot(paper) on.
4. Now when you turn it back off it will display an error while disabling the plugin.

**Expected behavior**
No error would show up.

**Platform and Versions (please complete the following information):**
 - OS: CentOS 8
 - Java Version: OpenJDK 14.0.1
 - MultiChat Version: 1.9
 - Proxy Version: Waterfall-341
 - Local Server Version: git-Paper-226 (1.15.2)

**Configuration files:**
MultiChatLocal: https://gist.github.com/FaberoM/486297a0e4a95452ea9fae0576b92e0d
MultiChatBungee: https://gist.github.com/FaberoM/285e5fd31aa9ae58b8c7f5bcce404a1e

**Comment by OllieMartin** [comment]
Thanks for this!

Where I had changed the database name from "multichatspigot.db" to "multichatlocal.db", it looks like I missed the line of code to disable it in the shutdown!

I will release a fix in a few minutes!

**Comment by OllieMartin** [comment]
https://www.spigotmc.org/resources/multichat.26204/update?update=333298

**Comment by FaberoM** [comment]
Wow, that was a fast one! :P Thank you for your hard work again.
